work:
  w1pmsipilot:
    name: PMSIpilot
    begin: Septembre 2010
    end: Présent
    position: Web Développeuse
    description: "Employée au sein de l'équipe de R&D, j'ai aussi bien fait de la résolution de bugs que participé à la conception d'architectures. La méthodologie inspirée de Scrum m'a appris l'agilité."
  w2orupaca:
    name: ORUPACA
    begin: Juillet 2009
    end: Juillet 2010
    position: Web Développeuse
    description: "Dans ce GIP (Groupement d'Intérêt Public), j'ai participé à tout les aspects de la vie d'un projet (via différents projets) : la conception en prenant en compte les besoins clients, le développement, la mise en production, la maintenance (résolution de bugs et évolutions), ainsi que le contact client de type support logiciel."
known:
  k1:
    name: Développement Web
    list:
      - (x)HTML
      - notions de HTML5
      - javascript (+ jquery)
      - CSS(3)
  k2:
    name: Ruby
    list:
      - ruby (7ans)
      - "frameworks : rails (1an), sinatra, jekyll"
      - "templating : haml, liquid"
  k3:
    name: Php
    list:
      - php (4ans)
      - "frameworks : symfony 1.4 (2ans)"
  k4e:
    name: Bases de données
    list:
      - MySQL (MyISAM et InnoDB)
      - MongoDB
      - PostgreSQL
  k5stock:
    name: Structuration de données
    list:
      - XML
      - YAML
      - JSON
  k6test:
    name: Testing
    list: 
      - Utilisation de Jenkins
      - Tests unitaires 
      - Tests fonctionnels
  k7methodo:
    name: Méthodologies
    list:
      - scrum
      - pomodoro
  k8other:
    name: Autre
    list:
      - "OS : Linux (ubuntu / debian), Windows"
      - "notions d'utilisation de the Gimp2"
      - utilisation de git
studies:
  fac:
    name: Licence informatique
    begin: 2008
    end: 2009
    position: Université du Havre
    description: "Diplôme obtenu : Licence informatique"
  dut:
    name: DUT Informatique
    begin: 2006
    end: 2008
    position: IUT du Havre
    description: "Diplôme obtenu : DUT informatique option génie logiciel"
    
  
