work:
  w0novagile:
    name: "<a href='http://novagile.fr' target='_blank' rel='nofollow'>Novagile</a>"
    begin: "Octobre 2011"
    end: "Présent"
    position: "Web Développeuse (Ruby/Rails)"
    description: "Dans une équipe de taille réduite, je travaille sur différents projets en Ruby on Rails. J'ai pu découvrir des projets avec plus de fréquentation que ce dont j'avais pu avoir l'habitude auparavant, comme <a href='http://bookandgolf.com/' target='_blank' rel='nofollow'>Book And Golf</a> ; mais aussi des technologies beaucoup plus orientées Front, comme backbone.js sur <a href='http://clubchauffeur.com' target='_blank' rel='nofollow'>Club Chauffeur</a>.<br />Mes connaissances pour des tests plus cohérents, pertinents et complets se sont approfondies, et nous travaillons avec des revues de codes systématiques afin de partager nos points de vues et bonnes pratiques."
  w1pmsipilot:
    name: "PMSIpilot"
    begin: "Septembre 2010"
    end: "Octobre 2011"
    position: "Web Développeuse (Php)"
    description: "Employée au sein de l'équipe de R&D, j'ai aussi bien fait de la résolution de bugs que participé à la conception d'architectures. La méthodologie inspirée de Scrum m'a appris l'agilité."
  w2orupaca:
    name: "ORUPACA"
    begin: "Juillet 2009"
    end: "Juillet 2010"
    position: "Web Développeuse (Php)"
    description: "Dans ce GIP (Groupement d'Intérêt Public), j'ai participé à tout les aspects de la vie d'un projet (via différents projets) : la conception en prenant en compte les besoins clients, le développement, la mise en production, la maintenance (résolution de bugs et évolutions), ainsi que le contact client de type support logiciel."
known:
  k2:
    name: "Ruby"
    list:
      - "Ruby <small>(7ans)</small>"
      - "Frameworks : rails <small>(2 ans)</small>, sinatra, jekyll"
  k3:
    name: "Bases de données"
    list:
      - "PostgreSQL"
      - "MySQL <small>(MyISAM et InnoDB)</small>"
      - "MongoDB"
  k4:
    name: "Testing"
    list: 
      - "Jenkins, Travis"
      - "Tests unitaires <small>(rspec, factory_girl, VCR)</small>" 
      - "Tests d'acceptance <small>(rspec, capybara)</small>"
  k5:
    name: "Javascript"
    list:
      - "Librairie : JQuery"
      - "Framework : Backbone.js"
  k8:
    name: "Intégration"
    list:
      - "HTML5"
      - "HAML"
      - "Sass"
      - "CSS3"
  k9:
    name: Autre
    list:
      - "OS : Linux (ubuntu / debian), Windows"
      - "VCS : git, svn"
studies:
  fac:
    name: Licence informatique
    begin: 2008
    end: 2009
    position: Université du Havre
  dut:
    name: DUT Informatique option génie logiciel
    begin: 2006
    end: 2008
    position: IUT du Havre
    
  
